version: '3.7'

services:
  # SEQ Log Server
  seq:
    image: datalust/seq:latest
    restart: always
    volumes:
      - seq:/data
    env_file:
      - .env
    ports:
      # - 5566:5341 # Example for port changing
      - 5341
    environment:
      - ACCEPT_EULA=Y
      - SEQ_API_CANONICALURI=https://${HOST}
      - LETSENCRYPT_HOST=${HOST}
      - VIRTUAL_HOST=${HOST}
      - VURTUAL_PORT=80
    networks:
      - proxy-tier
      - default

  # Accepts GELF format messages via UDP or TCP and writes them to Seq
  seq-input-gelf:
    image: datalust/seq-input-gelf:latest
    depends_on:
      - seq
    restart: always
    ports:
      # - '12345:12201/udp' # Example for port changing
      - '12201:12201/udp'
    environment:
      - SEQ_ADDRESS=http://seq:5341
      # - SEQ_API_KEY=
      # - GELF_ADDRESS=udp://0.0.0.0:12201
      # - GELF_ENABLE_DIAGNOSTICS=True

volumes:
  seq:

networks:
  proxy-tier:
    external: true
    name: proxy-tier
