version: '3.7'

x-labels:
  labels: &default-label
    seq:

services:
  # SEQ Log Server
  seq:
    image: datalust/seq:latest
    labels: *default-label
    restart: always
    volumes:
      - seq:/data
    env_file:
      - .env
    ports:
      - 5341
    environment:
      - ACCEPT_EULA=Y
      - SEQ_API_CANONICALURI=https://${HOST}
      - LETSENCRYPT_HOST=${HOST}
      - VIRTUAL_HOST=${HOST}
      - VURTUAL_PORT=80
    networks:
      - proxy-tier
      - default

  # Accepts GELF format messages via UDP or TCP and writes them to Seq
  seq-input-gelf:
    image: datalust/seq-input-gelf:latest
    labels: *default-label
    depends_on:
      - seq
    restart: always
    ports:
      - '12201-12201:12201'
      - '12201:12201/udp'
    environment:
      - SEQ_ADDRESS=http://seq:5341
      # - GELF_ENABLE_DIAGNOSTICS=True

  jobber:
    image: blacklabelops/jobber:docker
    restart: always
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./:/docker-compose:ro
    environment:
      ## JOB number must start from 1
      - JOB_NAME1=Backup
      - JOB_COMMAND1=/bin/bash cd /docker-compose && docker-compose start backup
      - JOB_TIME1=0 0 0 * * 2 #Exec per Week at UTC Tue. 0 a.m.
      - JOB_NOTIFY_ERR1=true
      - JOB_NOTIFY_FAIL1=true

  backup:
    build: ./volume-backup
    depends_on:
      - seq
      - seq-input-gelf
    restart: "no"
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - seq:/volume
      - ${BACKUP_FOLDER}:/backup
    environment:
      - BACKUP_LABEL=seq
    secrets:
      - rsyncpass
    command: >
      /bin/bash -c "/bin/bash /script/backup.sh && 
                    /bin/bash /script/upload.sh"

volumes:
  seq:
    labels: *default-label

networks:
  proxy-tier:
    external: true
    name: proxy-tier

secrets:
  rsyncpass:
    file: ~/ssh.pas
