version: '3.7'

x-labels:
  labels: &default-label
    seq:

services:
  restore:
    build: ./volume-backup
    restart: "no"
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - seq:/volume 
      - ${BACKUP_FOLDER}:/backup
    environment:
      - BACKUP_LABEL=seq
    command: /bin/bash /script/restore.sh

volumes:
  seq:
    labels: *default-label
